# Generated by Django 4.0.3 on 2022-03-23 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_lessonview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonview',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.lesson'),
        ),
    ]
